version: '3.8'

services:
  postgres:
    image: postgres:latest
    container_name: postgres-local
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: e2e
      POSTGRES_USER: user
      POSTGRES_PASSWORD: hardcode
    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
  postgres-data:
